id: AA604938F
base_file: f8E3C.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:30:15.816590
  last_modified_at: 2022-06-11 13:30:15.816597
