id: AA604938F
base_file: f4391.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:30:15.810644
  last_modified_at: 2022-06-11 13:30:15.810647
