id: AA604938F
base_file: f48FB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:30:15.811896
  last_modified_at: 2022-06-11 13:30:15.811899
