id: AA604938F
base_file: f58DD.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:30:15.813224
  last_modified_at: 2022-06-11 13:30:15.813229
