id: AA604938F
base_file: f2A7C.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:30:15.809160
  last_modified_at: 2022-06-11 13:30:15.809166
