id: AA604938F
base_file: f1E64.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:30:15.806173
  last_modified_at: 2022-06-11 13:30:15.806181
